/**
 * Compile the AudioWorklet processor to a standalone ES module.
 *
 * AudioWorklet modules are loaded by URL with `audioWorklet.addModule()`, so they
 * cannot participate in the Next.js bundle graph. Compiling the processor
 * separately with esbuild is what lets it `import` the real DSP implementation
 * from src/dsp instead of carrying a second, divergent copy of the maths.
 */

import { build } from 'esbuild';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const entry = path.join(root, 'src/audio/worklet/meterProcessor.ts');
const outfile = path.join(root, 'public/worklets/meter-processor.js');

await mkdir(path.dirname(outfile), { recursive: true });

const result = await build({
  entryPoints: [entry],
  outfile,
  bundle: true,
  format: 'esm',
  platform: 'browser',
  // AudioWorklet requires a fairly modern baseline anyway; es2020 keeps the
  // output readable while supporting every browser that has AudioWorklet.
  target: ['es2020'],
  minify: process.env.NODE_ENV === 'production',
  sourcemap: process.env.NODE_ENV === 'production' ? false : 'inline',
  legalComments: 'none',
  logLevel: 'warning',
  metafile: true,
  alias: {
    '@': path.join(root, 'src'),
  },
  banner: {
    js: '/* Sonoscope meter AudioWorklet - generated by scripts/build-worklet.mjs. Do not edit. */',
  },
});

const bytes = Object.values(result.metafile.outputs).reduce((acc, o) => acc + o.bytes, 0);
console.log(`[build-worklet] wrote public/worklets/meter-processor.js (${(bytes / 1024).toFixed(1)} kB)`);
